### PR TITLE
Display contents of the selected dataset in a separate window

### PR DESCRIPTION
**Pull request by crisely09**
- Added some little button icons to the displayed in the contents.

- Also read the dataset and create an array to check the length, for later open a table window.

### CODE REVIEW

**Comment by anilbey** [comment]
Update

The table windows can be opened/closed when a tabular dataset is selected.

Screenshot 2023-01-18 at 23 05 21

Issues

1. checkbox of the table doesn't stay checked, it goes back to the default behaviour immediately

I think it is because of this line. It creates a new default `TableWindow` object each time.
Maybe it can store the references to those objects somehow.
This issue does not exist on the EGUI's table_demo.rs demo. Try to see how they did it.
This issue is not so critical as the table view is going to be read-only (i.e. users cannot change the values, they can just display).

```rust
let mut table_box = Box::<super::table::TableWindow>::default();
```

**Comment by crisely09** [comment]
There is also an error happening in some cases, for example when clicking the /general/experiment_description item the window disappears and gives the following error:
```
split_name = ["", "general", "experiment_description"]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: no conversion paths found', src/gui.rs:76:34
note: run with `RUST_BACKTRACE=1` environment variable to display a `backtrace`
```

**Comment by anilbey** [comment]
We should remove the upwrap calls there and treat those exceptions.

**Comment by adrien-berchet** [comment]
As far as I can see, we have to handle two cases:
* scalar datasets that contain metadata (like in `experiment_description`).
* array datasets that contain the actual data.

For scalar datasets we should use the following:
```rust
let x_data: hdf5::types::VarLenUnicode = group
                                .handler
                                .dataset(dataset)
                                .unwrap()
                                .read_scalar::<hdf5::types::VarLenUnicode>()
                                .unwrap();
```

**Comment by anilbey** [comment]
Ok, the hdf5 -> Rust type binding works now.

For `hdf5::types`, it appears we cannot get away with handling only Float, Integer and String. We have to handle all of them (the Rust way :) ). 

I was afraid handling all of those types would end-up in a lot of duplicated code. To address that I used the [generic types](https://doc.rust-lang.org/rust-by-example/generics.html). 

While working on generic types I learned something. Rust has a syntax to restrict the possible generic types.
E.g.
```Rust
impl<T: std::fmt::Display> TableWindow<T>
```
This will restrict the type `T` for those types that implement the `std::fmt::Display` trait.

Moreover, it allows us to restrict types that implement multiple traits.
E.g.
```Rust
    fn show_dataset<T: hdf5::H5Type + std::fmt::Display>(
```
This means that the `show_dataset` function takes the generic type `T` if and only if `T` implements all of the methods of `hdf5::H5Type` trait **and** `T` implements all of the methods of `std::fmt::Display` trait.

Here the restriction is mandatory. Inside the generic function body if we ever have to use a function from a trait, Rust forces us to restrict the generic type to that trait. Otherwise `T` could be a type that does not implement the `std::fmt` then the program could not compile.

nwbview-table-data-binding

Here the table can display string, float and integer types. Note that some data are represented as an array of a single element in the NWB file.

So far the table supports 1D data. The BBP NWBs contain also 2D data. We also need to handle the n-dimensional case. It shouldn't be so difficult I think.

and these types need to be handled as well :))

```rust
                                hdf5::types::TypeDescriptor::Unsigned(_) => todo!(),
                                hdf5::types::TypeDescriptor::Boolean => todo!(),
                                hdf5::types::TypeDescriptor::Enum(_) => todo!(),
                                hdf5::types::TypeDescriptor::Compound(_) => todo!(),
                                hdf5::types::TypeDescriptor::FixedArray(_, _) => todo!(),
                                hdf5::types::TypeDescriptor::FixedAscii(_) => todo!(),
                                hdf5::types::TypeDescriptor::FixedUnicode(_) => todo!(),
                                hdf5::types::TypeDescriptor::VarLenArray(_) => todo!(),
                                hdf5::types::TypeDescriptor::VarLenAscii => todo!(),
```

**Comment by adrien-berchet** [comment]
That's super nice @anilbey !!!
I pushed a minor fix to keep the scalar values displayed (they were just displayed in one frame and then they were disappearing) and I added a close button to hide the scalar values once they are displayed.

**Comment by anilbey** [comment]
Thanks @adrien-berchet, now we can display every data on our example NWB. :star_struck: 

In some NWB files the scalar unicode string can be very long to be displayed. It may not fit the frame. Does it make sense to add a slider (that slides left-to-right) in that case? Like in here: https://github.com/emilk/egui/blob/master/crates/egui_demo_lib/src/demo/table_demo.rs#L89

**Comment by crisely09** [comment]
You guys are great, this is amazing progress. 
I vote yes for the sliders 😄

**Comment by adrien-berchet** [comment]
I am not sure this kind of slider will make it. Wouldn't it be easier to just open a new Window as we do for other data? But in this one we would just write one String, so the user could move it, resize it, and so on.

**Comment by anilbey** [comment]
Good idea, a text box window will be more flexible.

**Review by adrien-berchet — APPROVED** [review]
Looks nice!
Now I think it's usable so it would be nice if we can have some testers to give their feedback.

**Comment by crisely09** [comment]
Uhhh nice, looks good. Sure, merge it.

I remember there was some plan to have other plot functionalities, but that can be a separate MR.

**Comment by anilbey** [comment]
> Now I think it's usable so it would be nice if we can have some testers to give their feedback.

BBP NWBs have 2D datasets, that represents the 2 axes for plotting the voltage or current against time. Once we support that, our scientists can use it I think.

**Comment by anilbey** [comment]
> I remember there was some plan to have other plot functionalities, but that can be a separate MR.

Yes, let's do it in another MR. The window with panels demo of EGUI can help there.

**Comment by adrien-berchet** [comment]
> > Now I think it's usable so it would be nice if we can have some testers to give their feedback.
> 
> BBP NWBs have 2D datasets, that represents the 2 axes for plotting the voltage or current against time. Once we support that, our scientists can use it I think.

Ah yeah, I forgot about this :)

**Comment by anilbey** [comment]
Alright merging, thank you both :)

**Pull request merged**
