### PR TITLE
Add a close button to the loaded files

### PR DESCRIPTION
**Pull request by adrien-berchet**

### CODE REVIEW

**Comment by anilbey** [comment]
Great! 

There was an egui demo app with a nice "X" button for closing.
I think that can be good here. What do you think?
X-buttons

**Comment by adrien-berchet** [comment]
Ah yes indeed it would be even better! I didn't see this, where is it? Did you already implemented it?

**Comment by anilbey** [comment]
I just added a commit, feel free to change or revert it.

**Review by anilbey — APPROVED** [review]

**Comment by adrien-berchet** [comment]
Ah yes, you implemented it :)
Thanks for the commit!

**Pull request merged**
