### PR TITLE
Release nwbview 0.2.4

### PR DESCRIPTION
**Pull request by anilbey**
The release solves #33.

I was wrong about the include directive of cargo.toml. It is not needed when I compile it on the project directory but the `cargo publish` command compiles it in a different directory and the static/icon.png needs to be copied there to be present at compile time.

```
@@ -14,7 +14,8 @@ include = [
  "Cargo.lock",
  "Cargo.toml",
  "LICENSE",
  "src/**/*"
  "src/**/*",
  "static/icon.png",
]
```

### CODE REVIEW

**Comment by adrien-berchet** [comment]
Ah :sweat_smile:

**Comment by adrien-berchet** [comment]
And did you see https://github.com/brainhack-ch/nwbview/pull/34#discussion_r1135787300 ?

**Comment by anilbey** [comment]
Oh, I didn't. :) Now I see. Reading...

**Comment by anilbey** [comment]
Thanks it is simpler now :)

**Comment by adrien-berchet** [comment]
You're welcome :)
Now it looks good to me!

**Review by adrien-berchet — APPROVED** [review]

**Pull request merged**
